AWSTemplateFormatVersion: '2010-09-09'

Description: CFN Lab 004 Workshop - AWS S3 template.

Parameters:
  EnvironmentType:
    Description: 'Specify the Environment type of the stack.'
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: 'Specify either dev, test or prod.'

Resources:
  CFNBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'cfn-workshop-04-${AWS::Region}-${EnvironmentType}-${AWS::AccountId}'
      VersioningConfiguration:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-versioningconfig.html
        # Allowed values: Enabled | Suspended
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  BucketName:
    Value: !Ref CFNBucket
    Description: S3 Bucket Name
